name: Check style and dist build

on: [push, pull_request]

jobs:
  check_style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade black flake8 wheel mypy setuptools
    - name: Check style
      run: make style_check
    - name: Check dist
      run: make dist
